---
commitizen:
  name: cz_customize
  customize:
#    message_template: "{{change_type}}:{% if show_message %} {{message}}{% endif %}"
#    example: 'feature: this feature enable customize through config file'
    schema: "<type>: <body>"
    schema_pattern: "(major|break|feat|fix|hotfix):(\\s.*)"
    bump_pattern: "^(break|feat|fix|hotfix)"
    commit_parser: "^(?P<change_type>feature|bug fix):\\s(?P<message>.*)?"
    changelog_pattern: "^(feature|bug fix)?(!)?"
    change_type_map:
      feature: Feat
      bug fix: Fix
    bump_map:
      break: MAJOR
      feat: MINOR
      fix: PATCH
      hotfix: PATCH
      major: MAJOR
    change_type_order: ["BREAKING CHANGE", "feat", "fix", "refactor", "perf"]
#    info_path: cz_customize_info.txt
#    info: This is customized info
#    questions:
#      - type: list
#      name: change_type
#      choices:
#        - value: feature
#        name: 'feature: A new feature.'
#      - value: bug fix
#        name: 'bug fix: A bug fix.'
#      message: Select the type of change you are committing
#    - type: input
#      name: message
#      message: Body.
#    - type: confirm
#      name: show_message
#      message: Do you want to add body message in commit?
  tag_format: $version
  update_changelog_on_bump: true
  version_provider: scm
  version_scheme: semver
  annotated_tag: true
 
